name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@203.161.52.96 << 'EOF'
            #!/bin/bash
        
            # Define the project directory
            PROJECT_DIR="/home/wpt/public_html/wptom-astro"
        
            # Check if the directory exists
            if [ -d "$PROJECT_DIR" ]; then
              # If the directory exists, change to that directory and pull the latest changes
              cd "$PROJECT_DIR"
              git pull origin main
            else
              # If the directory does not exist, clone the repository into that directory
              git clone https://github.com/wptom/wptom-astro.git "$PROJECT_DIR"
              cd "$PROJECT_DIR"
            fi
          
            # delete /home/wpt/public_html/wptom-astro/dist
            # cd "$PROJECT_DIR"
            # rm -rf dist
        
            # Install dependencies and build the project. Ignore any vulnerabilities or errors
            npm install
            npm audit fix --force
        
            # Check and build the project. Ignore errors
            astro build
          EOF
