name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@203.161.52.96 '
            #!/bin/bash
          
            # Change directory to the location of the project
            cd /home/wpt/public_html
            # Pull the latest changes from the repository
            git pull https://github.com/wptom/wptom-astro.git
            cd wptom-astro
            npm install
            npm audit fix
            npm run build
          '